optional:mosip.kernel.keymanager.signature.kid.prepend
required:mosip.certify.credential-config.proof-types-supported
optional:mosip.certify.data-provider-plugin.credential-status.supported-purposes
required:mosip.certify.credential-config.cryptographic-binding-methods-supported
required:mosip.certify.credential-config.credential-signing-alg-values-supported
required:mosip.certify.data-provider-plugin.did-url
optional:mosip.certify.cache.redis.key-prefix
required:mosip.certify.credential-config.issuer.display