optional:mosip.kernel.keymanager.signature.kid.prepend
required:mosip.certify.credential-config.proof-types-supported
required:mosip.certify.credential-config.cryptographic-binding-methods-supported
required:mosip.certify.credential-config.credential-signing-alg-values-supported
optional:mosip.certify.cache.redis.key-prefix
required:mosip.certify.credential-config.issuer.display